### ISSUE TITLE
Lens operator cheatsheet

### ISSUE THREAD

**Issue by neongreen** [aelve/guide#101]
See https://github.com/aelve/microlens/issues/79. This is blocked for now because we don't have support for tables.

**Comment by dbaynard** [comment]
I'm keen to help here. What's the specific table issue?

**Comment by neongreen** [comment]
@dbaynard Well, [cmark](https://github.com/jgm/cmark) doesn't support tables yet. That's pretty much it.

I think there are two options:

1. You can just write a cheatsheet in ASCII and we'll find some place to put it.

2. You can add ad-hoc support for tables by post-processing cmark's AST; e.g. a list of lists with a special first element `# TABLE` would be converted to a table. If you implement it in Guide, I'll merge it.

**Comment by neongreen** [comment]
@dbaynard have you decided anything? :)

**Comment by dbaynard** [comment]
I wonder whether this does, in fact, present an opportunity. Lens operators form a language and not having a table presents an opportunity to demonstrate this; I don't know how that would fit with the goals of the guide, though.
