### ISSUE TITLE
If a title is too long, it breaks the alignment of the columns

### ISSUE THREAD

**Issue by sternenseemann** [aelve/guide#128]
![2016-08-27-175609_1891x958_scrot](https://cloud.githubusercontent.com/assets/3154475/18028436/99a9cffa-6c7f-11e6-9369-8c8aac46cc2b.png)

**Comment by mrkkrp** [comment]
@neongreen, Also note on this screenshot it's visible that the site is rendered with different font than it's renderend for me for example. Would it make sense to use Google Fonts or similar service to make it render the same for all users?

**Comment by sternenseemann** [comment]
@mrkkrp That does not make sense. The site uses the default `sans-serif` font of the browser, I changed mine, so that's the expected behavior in this case.

As a side-note I highly discourage using google fonts since it discloses the user's surfing activity to the service.

**Comment by neongreen** [comment]
This will be fixed when we finish rewriting the frontend. Any day now!

**Comment by neongreen** [comment]
(https://staging.guide.aelve.com)
