### ISSUE TITLE
Haskell exercises

### ISSUE THREAD

**Issue by neongreen** [aelve/guide#186]
People are constantly linking to [99 Haskell Problems](https://wiki.haskell.org/H-99:_Ninety-Nine_Haskell_Problems), despite the fact that they are not particularly good. We should write our own and steal PRECIOUS PAGEVIEWS.

**Comment by zanzix** [comment]
That's a good idea!

Can we get some domain-specific stuff rather than just number theory stuff like Project Euler has? Something 'concrete-sounding' like that [tower-blocks with water](https://drive.google.com/file/d/0B59Tysg-nEQZUkdRT2lfUVM3cVk/edit) puzzle that's been talked about recently.

**Comment by neongreen** [comment]
Definitely domain-specific, though at first we should probably just cover what H99 covers (lists, etc) and go from there.

**Comment by neongreen** [comment]
https://www.notion.so/aelve/Exercises-df5faac904084588b61ff34f3c14565f
