### ISSUE TITLE
Get rid of absolute links

### ISSUE THREAD

**Issue by vrom911** [aelve/guide#195]
grep [absolute-links] to find up-to-date todo.

- [ ] [JS](https://github.com/aelve/guide/blob/master/src/Guide/JS.hs#L142)
- [ ] [Handlers](https://github.com/aelve/guide/blob/master/src/Guide/Handlers.hs#L353)
- [ ] Views
     - [ ] [Views](https://github.com/aelve/guide/blob/master/src/Guide/Views.hs#L729)
     - [ ] [Views.Utils](https://github.com/aelve/guide/blob/master/src/Guide/Views/Utils.hs#L255)
     - [ ] [Views.Category](https://github.com/aelve/guide/blob/master/src/Guide/Views/Category.hs#L73)
- [ ] [Main](https://github.com/aelve/guide/blob/master/src/Guide/Main.hs#L306)

**Comment by neongreen** [comment]
This issue is obsolete (new frontend is coming).
