### ISSUE TITLE
Allow editing a single section in the notes

### ISSUE THREAD

**Issue by neongreen** [aelve/guide#20]

**Comment by neongreen** [comment]
Currently the plan is as follows:

* each paragraph has a hash (the hash includes the paragraph's heading)
* we send a request like “edit paragraph with hash X”
* that's all

Later when there's merge-stuff: we also try to merge paragraph X with the rest of the text. But I don't yet know how (replacing the paragraph in the client-side text and merging with *that* is a bad solution, but how could merging of a paragraph and -text possibly containing that paragraph- done in general? I've no idea)

**Comment by mrkkrp** [comment]
What hash do you use?

**Comment by neongreen** [comment]
SHA-1, maybe. It shouldn't matter as long as there's no chance of collisions.

**Comment by mrkkrp** [comment]
Well, with some hashes it's possible to purposely create content that has colliding hash with any given content. SHA-1 is a cpyptographic hash and it's safe in tihs sense.

**Comment by neongreen** [comment]
Ugh, this is more complicated than I thought.

* 2 sections can have the same hash (if they have same content and same names). In this case we also want to send some kind of section path/index/whatever to disambiguate.

* Cheapskate doesn't provide a way to get the source of a block. Either we fork Cheapskate, or switch to another library (cmark seems to be the only option).

**Comment by neongreen** [comment]
Also, I should keep this in mind: sections can't be rendered independently, due to links:

~~~
# foo

[x][x]

[x]: http://google.com

# bar

[google][x] links to http://google.com now
~~~

**Comment by neongreen** [comment]
Btw, we might not need this after all if #169 (and related) is done.
