### ISSUE TITLE
Integrate Gitlab CI with Github

### ISSUE THREAD

**Issue by neongreen** [aelve/guide#200]
It'd be nice to have the fast CI integrated with Github. We can probably do that by doing a [POST query](https://developer.github.com/v3/repos/statuses/) in `on_failure` and `on_success` jobs of the build – see http://docs.gitlab.com/ce/ci/yaml/README.html#when.

**Comment by AaronFriel** [comment]
Just as a note, this probably wouldn't work for pull requests without a change to [grapple](https://github.com/aaronfriel/grapple), the tool I wrote to sync repositories.

**Comment by neongreen** [comment]
Can likely be done with Circle CI's granular caches.
