### ISSUE TITLE
INSTALL.md misses a command in 'How to install locally' section

### ISSUE THREAD

**Issue by vsavkov** [aelve/guide#220]
INSTALL.md for local installation misses a command to build bundle.js.
It should look  like:
```
$ stack build
$ scripts/buildjs.sh # to build bundle.js
$ stack exec guide
```

**Comment by neongreen** [comment]
`stack build` should run it 🤔

https://github.com/aelve/guide/blob/master/Setup.hs#L13

Do you have any idea why it doesn't do that for you? Maybe you could post the logs here?

**Comment by vsavkov** [comment]
Found in the log
`./scripts/buildjs.sh: line 5: npm: command not found`. My fault.
I use `nvm` to setup `nodejs/npm` environment per project and didn't do that before `stack build`.
Probably a note that `npm` is required would help.

**Comment by neongreen** [comment]
Fixed in the `vue` branch.

**Comment by neongreen** [comment]
(All development happens there nowadays.)
