### ISSUE TITLE
Paragraph spacing is inconsistent

### ISSUE THREAD

**Issue by neongreen** [aelve/guide#319]
# Good: category summaries

![image](https://user-images.githubusercontent.com/1523306/60887010-053bb200-a25c-11e9-8c70-8dd633e9d264.png)

# Bad: item summaries

![image](https://user-images.githubusercontent.com/1523306/60886946-de7d7b80-a25b-11e9-8c95-b961d81e9c3b.png)

**Comment by avele** [comment]
Fixed in f0b20a2
