### ISSUE TITLE
Blank lines in code are not highlighted as code in the editor

### ISSUE THREAD

**Issue by neongreen** [aelve/guide#359]
![image](https://user-images.githubusercontent.com/1523306/62427918-05b45500-b703-11e9-8b41-b123b9421471.png)

**Comment by neongreen** [comment]
It should look like this:

![image](https://user-images.githubusercontent.com/1523306/62427934-3a281100-b703-11e9-9588-65a9cae4ff22.png)

**Comment by avele** [comment]
fixed in c9d512c
