### ISSUE TITLE
Show status in the category title

### ISSUE THREAD

**Issue by neongreen** [aelve/guide#60]
![screenshot from 2016-06-19 03-01-20](https://cloud.githubusercontent.com/assets/1523306/16174428/1c1eff6a-35ca-11e6-8f51-1c6e83f9fc1e.png)

Currently categories look like this. However, it might be good to somehow show category status (stub, work in progress, etc) in the header.

How to fix it:
- change generated HTML in src/View.hs (`renderCategoryInfo`)
- possibly change rules in static/css.css

**Comment by 2016rshah** [comment]
Has this already been [implemented](https://github.com/aelve/guide/blob/master/lib/View.hs#L715)?

**Comment by neongreen** [comment]
Nope, you're looking at the code for a `<select>` in the form that appears when you edit a category.

![image](https://cloud.githubusercontent.com/assets/1523306/19211440/dc84a2ec-8d44-11e6-9c75-2bbdb1801470.png)

**Comment by neongreen** [comment]
a 5-minute sketch with Chrome devtools:

![image](https://cloud.githubusercontent.com/assets/1523306/21715958/7a121732-d418-11e6-8d95-9beac2856a6d.png)
