### ISSUE TITLE
Blue links on red background look awful

### ISSUE THREAD

**Issue by neongreen** [aelve/guide#63]
![screenshot from 2016-06-19 02-58-42](https://cloud.githubusercontent.com/assets/1523306/16174420/bda773fe-35c9-11e6-9017-47350c373031.png)

How to fix it:
- figure out a nicer way to display unfinished categories
- change rules in static/css.css and possibly HTML in src/View.hs (`renderCategoryList`)

**Comment by danhannigan** [comment]
I agree that the red is & blue is tough to read... but it's also difficult to discern what are you trying to address by highlighting them in red? That they shouldn't be used, or a warning that they're unfinished? Without clarification, a key of sorts maybe, it's hard to know why they're called out in the first place.

**Comment by neongreen** [comment]
It says “stub” and “mostly done” next to the links, so they are different degrees of “unfinished”. Interestingly, you're the third person (out of three!) who haven't noticed the key, which means that providing a key (at least of this kind) is a bad solution, and a better one should be found.

**Comment by mrkkrp** [comment]
How about displaying an icon (with `title` attribute or user can hover over it) next to the title?

**Comment by danhannigan** [comment]
I was thinking the same thing @mrkkrp - some kind of icon. A warning symbol or something like that. 

Also, if they're "stub" and "mostly done" are you trying to discourage folks from using them entirely or just saying "Hey, use at your own risk?"

**Comment by neongreen** [comment]
Depends on the intentions of the user. If they want to improve the guide, then “stub” is an invitation to edit. If they want to get information, then “stub” is a warning that the information is incomplete (or even absent).

**Comment by neongreen** [comment]
> an invitation to edit

Specifically, I'm worried that a warning symbol won't convey this adequately, but maybe I'm wrong.

**Comment by danhannigan** [comment]
I can see the cause for worry with a warning icon - as it stands right now the red on blue makes me read "don't touch this" so maybe I'm drawing conclusions and basing my suggestions on that. A warning icon could have the same effect.

**Comment by neongreen** [comment]
What do you (well, everyone) think about this redesign? http://codepen.io/lightgreen/pen/KNVKpK

I haven't yet figured out what to do with “mostly done” though, so play with it and try to figure out something.

**Comment by mrkkrp** [comment]
I like it. :+1:

**Comment by int-index** [comment]
I like the redesign. It's easier on the eyes.

**Comment by neongreen** [comment]
Will deploy tomorrow after this is done:

* fix tests
* create an issue for overly thin underlines
* create (or update) an issue for “what's left to do” field

**Comment by neongreen** [comment]
Deployed.
