### ISSUE TITLE
Add buttons for pros/cons editing and other things

### ISSUE THREAD

**Issue by fkarg** [aelve/guide#93]
As there is a save-button for basically everything else except the pro/con section, it was very irritating to simply press enter.

Not that this is a bad thing, I even prefer it over the save-button, but it's simply misleading as there's nothing telling me that it'll save as soon as I hit enter, the first intuition is getting a new line instead.

So maybe adding an `simply press enter to save` label between the `[edit off]` and the `Markdown` might really prove useful.

**Comment by neongreen** [comment]
List of things we need buttons for:

* [ ] pros/cons
* [ ] search

**Comment by neongreen** [comment]
Buttons are present in the new frontend: https://staging.guide.aelve.com.
