### ISSUE TITLE
Instead of “changed X” say “added X” if X was added

### ISSUE THREAD

**Issue by neongreen** [aelve/guide#96]
Currently we have this, it's silly:

![image](https://cloud.githubusercontent.com/assets/1523306/16192534/8c82cf06-36f2-11e6-80b4-b4fb23179a48.png)

How to fix it:

* in src/View.hs, in `renderEdit` check for emptiness in branches like `Edit'SetCategoryNotes`, etc. and render them differently if they are empty

**Comment by babhishek21** [comment]
I believe the file `View.hs` resides in `/lib`and not `/src`.

**Comment by neongreen** [comment]
Yeah, it was moved together with the rest of `/src`.

**Comment by babhishek21** [comment]
So are we supposed to check for all the `Edit'Set*` cases to see if the old value is empty? What about when new values are empty?

**Comment by neongreen** [comment]
> So are we supposed to check for all the Edit'Set* cases to see if the old value is empty?

Yeah. I wish I had a less boilerplatey definition of `Edit` (with some kind of first-class record fields), but currently it is what it is, and I don't know how to make it better without losing type safety. If you have any ideas, please tell!

> What about when new values are empty?

They can't be, because code that generates `Edit`s won't create an edit when the old value is equal to the new value. Furthermore, even if an empty value slips through, nothing bad will happen (the admin interface isn't even visible for ordinary users), so you can ignore this possibility.

Here's the function which adds an edit: https://github.com/aelve/guide/blob/master/lib/Guide.hs#L180-L190. Here's the function which checks that an edit actually changes something: https://github.com/aelve/guide/blob/master/lib/Types.hs#L672-L711.

**Comment by babhishek21** [comment]
Great! I think I'll take a look today evening. Does anyone mind?

**Comment by neongreen** [comment]
I definitely don't!

**Comment by neongreen** [comment]
Fixed by @babhishek21 in #131 and deployed.
